name: chat2you
version: 1.0.0
publish_to: none
description: start your project in the fastest way
environment:
  sdk: ">=3.0.1 <4.0.0"

dependencies:
  cupertino_icons: ^1.0.6
  get: ^4.6.6

  logger: ^2.0.2+1

  flutter_screenutil: ^5.9.0

  dio: ^5.3.4
  http_mock_adapter: ^0.6.1
  pretty_dio_logger: ^1.3.1

  hive: ^2.2.3
  hive_flutter: ^1.1.0
  shared_preferences: ^2.2.0

  firebase_core: ^2.23.0
  firebase_messaging: ^14.7.0
  awesome_notifications: ^0.8.2

  flutter_launcher_icons: ^0.13.1
  change_app_package_name: ^1.1.0
  rename_app: ^1.3.1

  flutter_animate: ^4.3.0

  flutter_svg: ^2.0.9

  cached_network_image: ^3.3.0

  flutter:
    sdk: flutter
  email_validator: ^2.1.17

dev_dependencies:
  mockito: ^5.4.3
  flutter_lints: ^3.0.1
  build_runner: ^2.4.6
  hive_generator: ^2.0.1
  pub_semver: ^2.1.4

  integration_test:
    sdk: flutter

  flutter_test:
    sdk: flutter

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/app_icon.png"

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/vectors/
    - assets/fonts/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 300
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 700
    - family: Cairo
      fonts:
        - asset: assets/fonts/Cairo-Regular.ttf
          weight: 300
        - asset: assets/fonts/Cairo-Medium.ttf
          weight: 500
        - asset: assets/fonts/Cairo-SemiBold.ttf
          weight: 900
